* Encoding: UTF-8.

EXAMINE VARIABLES=pot_percent phos_percent mag_percent
  /PLOT BOXPLOT HISTOGRAM NPPLOT
  /COMPARE GROUPS
  /PERCENTILES(25,50,75) HAVERAGE
  /STATISTICS DESCRIPTIVES EXTREME
  /CINTERVAL 95
  /MISSING PAIRWISE
  /NOTOTAL.
